Added example for web js sdk
singnet/snet-sdk-js pull request #150
Opened 2024-10-15 13:17 UTC by MarinaFedy

2024-10-15 16:56 UTC, AlbinaPomogalova approved these changes

2024-10-16 12:49 UTC, serbinadrian requested changes

2024-10-16 12:49 UTC, serbinadrian commented on package-lock.json
REMOVE LOCKS via git rm
add to gitignore

2024-10-16 12:49 UTC, serbinadrian commented on package-lock.json
+ yarn.lock

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/README.md
> +### `npm start`
Wrap these commands into the code block to enable copying

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/public/index.html
> +    <!--
Remove comments

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/Loader/index.jsx
> +import "./styles.css";
ReactComponent is of ReactElement or ReactNode has to return something;
Consider ReactNode is returning null.

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/ServiceDemo/index.jsx
> +            {isComplited && <div className="service-output">
completed

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/ServiceDemo/index.jsx
> +    {value: "div", title: ":"},
consider /

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/ServiceDemo/index.jsx
> +    const [isDisable, setIsDisable] = useState(true);
isDisabled
and is[WHAT]Disabled

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/ServiceDemo/index.jsx
> +    const [isComplited, setIsComplited] = useState(false);
is[WHAT]Completed

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/ServiceDemo/index.jsx
> +            setIsLoading(true);
formatting!

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/ServiceDemo/index.jsx
> +        <>
Consider Fragment

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/ServiceInfo/index.jsx
> +                                <tr>
use meta map rendering

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/WalletInfo/index.jsx
> +        setIsLoading(true);
formatting!

2024-10-16 12:49 UTC, serbinadrian commented on packages/web/examples/calculator/src/components/WalletInfo/index.jsx
> +            <table className="wallet-info-table">
meta map

2024-10-16 14:11 UTC, serbinadrian approved these changes

2024-10-16 14:11 UTC, merged